// Generated from the official NeetCode repository metadata and public NeetCode catalog. Metadata only.
export const NEETCODE_CATALOG_VERSION = 'neetcode150-2026-09-22';
export const NEETCODE_CATALOG = Object.freeze([
  {
    "slug": "contains-duplicate",
    "title": "Contains Duplicate",
    "pattern": "Arrays & Hashing",
    "difficulty": "Easy",
    "order": 1,
    "questionUrl": "https://neetcode.io/problems/duplicate-integer",
    "sourceId": "duplicate-integer",
    "code": "0217-contains-duplicate",
    "python": true,
    "javascript": true
  },
  {
    "slug": "valid-anagram",
    "title": "Valid Anagram",
    "pattern": "Arrays & Hashing",
    "difficulty": "Easy",
    "order": 2,
    "questionUrl": "https://neetcode.io/problems/is-anagram",
    "sourceId": "is-anagram",
    "code": "0242-valid-anagram",
    "python": true,
    "javascript": true
  },
  {
    "slug": "two-sum",
    "title": "Two Sum",
    "pattern": "Arrays & Hashing",
    "difficulty": "Easy",
    "order": 3,
    "questionUrl": "https://neetcode.io/problems/two-integer-sum",
    "sourceId": "two-integer-sum",
    "code": "0001-two-sum",
    "python": true,
    "javascript": true
  },
  {
    "slug": "group-anagrams",
    "title": "Group Anagrams",
    "pattern": "Arrays & Hashing",
    "difficulty": "Medium",
    "order": 4,
    "questionUrl": "https://neetcode.io/problems/anagram-groups",
    "sourceId": "anagram-groups",
    "code": "0049-group-anagrams",
    "python": true,
    "javascript": true
  },
  {
    "slug": "top-k-frequent-elements",
    "title": "Top K Frequent Elements",
    "pattern": "Arrays & Hashing",
    "difficulty": "Medium",
    "order": 5,
    "questionUrl": "https://neetcode.io/problems/top-k-elements-in-list",
    "sourceId": "top-k-elements-in-list",
    "code": "0347-top-k-frequent-elements",
    "python": true,
    "javascript": true
  },
  {
    "slug": "product-of-array-except-self",
    "title": "Product of Array Except Self",
    "pattern": "Arrays & Hashing",
    "difficulty": "Medium",
    "order": 6,
    "questionUrl": "https://neetcode.io/problems/products-of-array-discluding-self",
    "sourceId": "products-of-array-discluding-self",
    "code": "0238-product-of-array-except-self",
    "python": true,
    "javascript": true
  },
  {
    "slug": "valid-sudoku",
    "title": "Valid Sudoku",
    "pattern": "Arrays & Hashing",
    "difficulty": "Medium",
    "order": 7,
    "questionUrl": "https://neetcode.io/problems/valid-sudoku",
    "sourceId": "valid-sudoku",
    "code": "0036-valid-sudoku",
    "python": true,
    "javascript": true
  },
  {
    "slug": "encode-and-decode-strings",
    "title": "Encode and Decode Strings",
    "pattern": "Arrays & Hashing",
    "difficulty": "Medium",
    "order": 8,
    "questionUrl": "https://neetcode.io/problems/string-encode-and-decode",
    "sourceId": "string-encode-and-decode",
    "code": "0271-encode-and-decode-strings",
    "python": true,
    "javascript": true
  },
  {
    "slug": "longest-consecutive-sequence",
    "title": "Longest Consecutive Sequence",
    "pattern": "Arrays & Hashing",
    "difficulty": "Medium",
    "order": 9,
    "questionUrl": "https://neetcode.io/problems/longest-consecutive-sequence",
    "sourceId": "longest-consecutive-sequence",
    "code": "0128-longest-consecutive-sequence",
    "python": true,
    "javascript": true
  },
  {
    "slug": "valid-palindrome",
    "title": "Valid Palindrome",
    "pattern": "Two Pointers",
    "difficulty": "Easy",
    "order": 10,
    "questionUrl": "https://neetcode.io/problems/is-palindrome",
    "sourceId": "is-palindrome",
    "code": "0125-valid-palindrome",
    "python": true,
    "javascript": true
  },
  {
    "slug": "two-sum-ii-input-array-is-sorted",
    "title": "Two Sum II Input Array Is Sorted",
    "pattern": "Two Pointers",
    "difficulty": "Medium",
    "order": 11,
    "questionUrl": "https://neetcode.io/problems/two-integer-sum-ii",
    "sourceId": "two-integer-sum-ii",
    "code": "0167-two-sum-ii-input-array-is-sorted",
    "python": true,
    "javascript": true
  },
  {
    "slug": "3sum",
    "title": "3Sum",
    "pattern": "Two Pointers",
    "difficulty": "Medium",
    "order": 12,
    "questionUrl": "https://neetcode.io/problems/three-integer-sum",
    "sourceId": "three-integer-sum",
    "code": "0015-3sum",
    "python": true,
    "javascript": true
  },
  {
    "slug": "container-with-most-water",
    "title": "Container With Most Water",
    "pattern": "Two Pointers",
    "difficulty": "Medium",
    "order": 13,
    "questionUrl": "https://neetcode.io/problems/max-water-container",
    "sourceId": "max-water-container",
    "code": "0011-container-with-most-water",
    "python": true,
    "javascript": true
  },
  {
    "slug": "trapping-rain-water",
    "title": "Trapping Rain Water",
    "pattern": "Two Pointers",
    "difficulty": "Hard",
    "order": 14,
    "questionUrl": "https://neetcode.io/problems/trapping-rain-water",
    "sourceId": "trapping-rain-water",
    "code": "0042-trapping-rain-water",
    "python": true,
    "javascript": true
  },
  {
    "slug": "best-time-to-buy-and-sell-stock",
    "title": "Best Time to Buy And Sell Stock",
    "pattern": "Sliding Window",
    "difficulty": "Easy",
    "order": 15,
    "questionUrl": "https://neetcode.io/problems/buy-and-sell-crypto",
    "sourceId": "buy-and-sell-crypto",
    "code": "0121-best-time-to-buy-and-sell-stock",
    "python": true,
    "javascript": true
  },
  {
    "slug": "longest-substring-without-repeating-characters",
    "title": "Longest Substring Without Repeating Characters",
    "pattern": "Sliding Window",
    "difficulty": "Medium",
    "order": 16,
    "questionUrl": "https://neetcode.io/problems/longest-substring-without-duplicates",
    "sourceId": "longest-substring-without-duplicates",
    "code": "0003-longest-substring-without-repeating-characters",
    "python": true,
    "javascript": true
  },
  {
    "slug": "longest-repeating-character-replacement",
    "title": "Longest Repeating Character Replacement",
    "pattern": "Sliding Window",
    "difficulty": "Medium",
    "order": 17,
    "questionUrl": "https://neetcode.io/problems/longest-repeating-substring-with-replacement",
    "sourceId": "longest-repeating-substring-with-replacement",
    "code": "0424-longest-repeating-character-replacement",
    "python": true,
    "javascript": true
  },
  {
    "slug": "permutation-in-string",
    "title": "Permutation In String",
    "pattern": "Sliding Window",
    "difficulty": "Medium",
    "order": 18,
    "questionUrl": "https://neetcode.io/problems/permutation-string",
    "sourceId": "permutation-string",
    "code": "0567-permutation-in-string",
    "python": true,
    "javascript": true
  },
  {
    "slug": "minimum-window-substring",
    "title": "Minimum Window Substring",
    "pattern": "Sliding Window",
    "difficulty": "Hard",
    "order": 19,
    "questionUrl": "https://neetcode.io/problems/minimum-window-with-characters",
    "sourceId": "minimum-window-with-characters",
    "code": "0076-minimum-window-substring",
    "python": true,
    "javascript": true
  },
  {
    "slug": "sliding-window-maximum",
    "title": "Sliding Window Maximum",
    "pattern": "Sliding Window",
    "difficulty": "Hard",
    "order": 20,
    "questionUrl": "https://neetcode.io/problems/sliding-window-maximum",
    "sourceId": "sliding-window-maximum",
    "code": "0239-sliding-window-maximum",
    "python": true,
    "javascript": true
  },
  {
    "slug": "valid-parentheses",
    "title": "Valid Parentheses",
    "pattern": "Stack",
    "difficulty": "Easy",
    "order": 21,
    "questionUrl": "https://neetcode.io/problems/validate-parentheses",
    "sourceId": "validate-parentheses",
    "code": "0020-valid-parentheses",
    "python": true,
    "javascript": true
  },
  {
    "slug": "min-stack",
    "title": "Min Stack",
    "pattern": "Stack",
    "difficulty": "Medium",
    "order": 22,
    "questionUrl": "https://neetcode.io/problems/minimum-stack",
    "sourceId": "minimum-stack",
    "code": "0155-min-stack",
    "python": true,
    "javascript": true
  },
  {
    "slug": "evaluate-reverse-polish-notation",
    "title": "Evaluate Reverse Polish Notation",
    "pattern": "Stack",
    "difficulty": "Medium",
    "order": 23,
    "questionUrl": "https://neetcode.io/problems/evaluate-reverse-polish-notation",
    "sourceId": "evaluate-reverse-polish-notation",
    "code": "0150-evaluate-reverse-polish-notation",
    "python": true,
    "javascript": true
  },
  {
    "slug": "generate-parentheses",
    "title": "Generate Parentheses",
    "pattern": "Stack",
    "difficulty": "Medium",
    "order": 24,
    "questionUrl": "https://neetcode.io/problems/generate-parentheses",
    "sourceId": "generate-parentheses",
    "code": "0022-generate-parentheses",
    "python": true,
    "javascript": true
  },
  {
    "slug": "daily-temperatures",
    "title": "Daily Temperatures",
    "pattern": "Stack",
    "difficulty": "Medium",
    "order": 25,
    "questionUrl": "https://neetcode.io/problems/daily-temperatures",
    "sourceId": "daily-temperatures",
    "code": "0739-daily-temperatures",
    "python": true,
    "javascript": true
  },
  {
    "slug": "car-fleet",
    "title": "Car Fleet",
    "pattern": "Stack",
    "difficulty": "Medium",
    "order": 26,
    "questionUrl": "https://neetcode.io/problems/car-fleet",
    "sourceId": "car-fleet",
    "code": "0853-car-fleet",
    "python": true,
    "javascript": true
  },
  {
    "slug": "largest-rectangle-in-histogram",
    "title": "Largest Rectangle In Histogram",
    "pattern": "Stack",
    "difficulty": "Hard",
    "order": 27,
    "questionUrl": "https://neetcode.io/problems/largest-rectangle-in-histogram",
    "sourceId": "largest-rectangle-in-histogram",
    "code": "0084-largest-rectangle-in-histogram",
    "python": true,
    "javascript": true
  },
  {
    "slug": "binary-search",
    "title": "Binary Search",
    "pattern": "Binary Search",
    "difficulty": "Easy",
    "order": 28,
    "questionUrl": "https://neetcode.io/problems/binary-search",
    "sourceId": "binary-search",
    "code": "0704-binary-search",
    "python": true,
    "javascript": true
  },
  {
    "slug": "search-a-2d-matrix",
    "title": "Search a 2D Matrix",
    "pattern": "Binary Search",
    "difficulty": "Medium",
    "order": 29,
    "questionUrl": "https://neetcode.io/problems/search-2d-matrix",
    "sourceId": "search-2d-matrix",
    "code": "0074-search-a-2d-matrix",
    "python": true,
    "javascript": true
  },
  {
    "slug": "koko-eating-bananas",
    "title": "Koko Eating Bananas",
    "pattern": "Binary Search",
    "difficulty": "Medium",
    "order": 30,
    "questionUrl": "https://neetcode.io/problems/eating-bananas",
    "sourceId": "eating-bananas",
    "code": "0875-koko-eating-bananas",
    "python": true,
    "javascript": true
  },
  {
    "slug": "find-minimum-in-rotated-sorted-array",
    "title": "Find Minimum In Rotated Sorted Array",
    "pattern": "Binary Search",
    "difficulty": "Medium",
    "order": 31,
    "questionUrl": "https://neetcode.io/problems/find-minimum-in-rotated-sorted-array",
    "sourceId": "find-minimum-in-rotated-sorted-array",
    "code": "0153-find-minimum-in-rotated-sorted-array",
    "python": true,
    "javascript": true
  },
  {
    "slug": "search-in-rotated-sorted-array",
    "title": "Search In Rotated Sorted Array",
    "pattern": "Binary Search",
    "difficulty": "Medium",
    "order": 32,
    "questionUrl": "https://neetcode.io/problems/find-target-in-rotated-sorted-array",
    "sourceId": "find-target-in-rotated-sorted-array",
    "code": "0033-search-in-rotated-sorted-array",
    "python": true,
    "javascript": true
  },
  {
    "slug": "time-based-key-value-store",
    "title": "Time Based Key Value Store",
    "pattern": "Binary Search",
    "difficulty": "Medium",
    "order": 33,
    "questionUrl": "https://neetcode.io/problems/time-based-key-value-store",
    "sourceId": "time-based-key-value-store",
    "code": "0981-time-based-key-value-store",
    "python": true,
    "javascript": true
  },
  {
    "slug": "median-of-two-sorted-arrays",
    "title": "Median of Two Sorted Arrays",
    "pattern": "Binary Search",
    "difficulty": "Hard",
    "order": 34,
    "questionUrl": "https://neetcode.io/problems/median-of-two-sorted-arrays",
    "sourceId": "median-of-two-sorted-arrays",
    "code": "0004-median-of-two-sorted-arrays",
    "python": true,
    "javascript": true
  },
  {
    "slug": "reverse-linked-list",
    "title": "Reverse Linked List",
    "pattern": "Linked List",
    "difficulty": "Easy",
    "order": 35,
    "questionUrl": "https://neetcode.io/problems/reverse-a-linked-list",
    "sourceId": "reverse-a-linked-list",
    "code": "0206-reverse-linked-list",
    "python": true,
    "javascript": true
  },
  {
    "slug": "merge-two-sorted-lists",
    "title": "Merge Two Sorted Lists",
    "pattern": "Linked List",
    "difficulty": "Easy",
    "order": 36,
    "questionUrl": "https://neetcode.io/problems/merge-two-sorted-linked-lists",
    "sourceId": "merge-two-sorted-linked-lists",
    "code": "0021-merge-two-sorted-lists",
    "python": true,
    "javascript": true
  },
  {
    "slug": "reorder-list",
    "title": "Reorder List",
    "pattern": "Linked List",
    "difficulty": "Medium",
    "order": 37,
    "questionUrl": "https://neetcode.io/problems/reorder-linked-list",
    "sourceId": "reorder-linked-list",
    "code": "0143-reorder-list",
    "python": true,
    "javascript": true
  },
  {
    "slug": "remove-nth-node-from-end-of-list",
    "title": "Remove Nth Node From End of List",
    "pattern": "Linked List",
    "difficulty": "Medium",
    "order": 38,
    "questionUrl": "https://neetcode.io/problems/remove-node-from-end-of-linked-list",
    "sourceId": "remove-node-from-end-of-linked-list",
    "code": "0019-remove-nth-node-from-end-of-list",
    "python": true,
    "javascript": true
  },
  {
    "slug": "copy-list-with-random-pointer",
    "title": "Copy List With Random Pointer",
    "pattern": "Linked List",
    "difficulty": "Medium",
    "order": 39,
    "questionUrl": "https://neetcode.io/problems/copy-linked-list-with-random-pointer",
    "sourceId": "copy-linked-list-with-random-pointer",
    "code": "0138-copy-list-with-random-pointer",
    "python": true,
    "javascript": true
  },
  {
    "slug": "add-two-numbers",
    "title": "Add Two Numbers",
    "pattern": "Linked List",
    "difficulty": "Medium",
    "order": 40,
    "questionUrl": "https://neetcode.io/problems/add-two-numbers",
    "sourceId": "add-two-numbers",
    "code": "0002-add-two-numbers",
    "python": true,
    "javascript": true
  },
  {
    "slug": "linked-list-cycle",
    "title": "Linked List Cycle",
    "pattern": "Linked List",
    "difficulty": "Easy",
    "order": 41,
    "questionUrl": "https://neetcode.io/problems/linked-list-cycle-detection",
    "sourceId": "linked-list-cycle-detection",
    "code": "0141-linked-list-cycle",
    "python": true,
    "javascript": true
  },
  {
    "slug": "find-the-duplicate-number",
    "title": "Find The Duplicate Number",
    "pattern": "Linked List",
    "difficulty": "Medium",
    "order": 42,
    "questionUrl": "https://neetcode.io/problems/find-duplicate-integer",
    "sourceId": "find-duplicate-integer",
    "code": "0287-find-the-duplicate-number",
    "python": true,
    "javascript": true
  },
  {
    "slug": "lru-cache",
    "title": "LRU Cache",
    "pattern": "Linked List",
    "difficulty": "Medium",
    "order": 43,
    "questionUrl": "https://neetcode.io/problems/lru-cache",
    "sourceId": "lru-cache",
    "code": "0146-lru-cache",
    "python": true,
    "javascript": true
  },
  {
    "slug": "merge-k-sorted-lists",
    "title": "Merge K Sorted Lists",
    "pattern": "Linked List",
    "difficulty": "Hard",
    "order": 44,
    "questionUrl": "https://neetcode.io/problems/merge-k-sorted-linked-lists",
    "sourceId": "merge-k-sorted-linked-lists",
    "code": "0023-merge-k-sorted-lists",
    "python": true,
    "javascript": true
  },
  {
    "slug": "reverse-nodes-in-k-group",
    "title": "Reverse Nodes In K Group",
    "pattern": "Linked List",
    "difficulty": "Hard",
    "order": 45,
    "questionUrl": "https://neetcode.io/problems/reverse-nodes-in-k-group",
    "sourceId": "reverse-nodes-in-k-group",
    "code": "0025-reverse-nodes-in-k-group",
    "python": true,
    "javascript": true
  },
  {
    "slug": "invert-binary-tree",
    "title": "Invert Binary Tree",
    "pattern": "Trees",
    "difficulty": "Easy",
    "order": 46,
    "questionUrl": "https://neetcode.io/problems/invert-a-binary-tree",
    "sourceId": "invert-a-binary-tree",
    "code": "0226-invert-binary-tree",
    "python": true,
    "javascript": true
  },
  {
    "slug": "maximum-depth-of-binary-tree",
    "title": "Maximum Depth of Binary Tree",
    "pattern": "Trees",
    "difficulty": "Easy",
    "order": 47,
    "questionUrl": "https://neetcode.io/problems/depth-of-binary-tree",
    "sourceId": "depth-of-binary-tree",
    "code": "0104-maximum-depth-of-binary-tree",
    "python": true,
    "javascript": true
  },
  {
    "slug": "diameter-of-binary-tree",
    "title": "Diameter of Binary Tree",
    "pattern": "Trees",
    "difficulty": "Easy",
    "order": 48,
    "questionUrl": "https://neetcode.io/problems/binary-tree-diameter",
    "sourceId": "binary-tree-diameter",
    "code": "0543-diameter-of-binary-tree",
    "python": true,
    "javascript": true
  },
  {
    "slug": "balanced-binary-tree",
    "title": "Balanced Binary Tree",
    "pattern": "Trees",
    "difficulty": "Easy",
    "order": 49,
    "questionUrl": "https://neetcode.io/problems/balanced-binary-tree",
    "sourceId": "balanced-binary-tree",
    "code": "0110-balanced-binary-tree",
    "python": true,
    "javascript": true
  },
  {
    "slug": "same-tree",
    "title": "Same Tree",
    "pattern": "Trees",
    "difficulty": "Easy",
    "order": 50,
    "questionUrl": "https://neetcode.io/problems/same-binary-tree",
    "sourceId": "same-binary-tree",
    "code": "0100-same-tree",
    "python": true,
    "javascript": true
  },
  {
    "slug": "subtree-of-another-tree",
    "title": "Subtree of Another Tree",
    "pattern": "Trees",
    "difficulty": "Easy",
    "order": 51,
    "questionUrl": "https://neetcode.io/problems/subtree-of-a-binary-tree",
    "sourceId": "subtree-of-a-binary-tree",
    "code": "0572-subtree-of-another-tree",
    "python": true,
    "javascript": true
  },
  {
    "slug": "lowest-common-ancestor-of-a-binary-search-tree",
    "title": "Lowest Common Ancestor of a Binary Search Tree",
    "pattern": "Trees",
    "difficulty": "Medium",
    "order": 52,
    "questionUrl": "https://neetcode.io/problems/lowest-common-ancestor-in-binary-search-tree",
    "sourceId": "lowest-common-ancestor-in-binary-search-tree",
    "code": "0235-lowest-common-ancestor-of-a-binary-search-tree",
    "python": true,
    "javascript": true
  },
  {
    "slug": "binary-tree-level-order-traversal",
    "title": "Binary Tree Level Order Traversal",
    "pattern": "Trees",
    "difficulty": "Medium",
    "order": 53,
    "questionUrl": "https://neetcode.io/problems/level-order-traversal-of-binary-tree",
    "sourceId": "level-order-traversal-of-binary-tree",
    "code": "0102-binary-tree-level-order-traversal",
    "python": true,
    "javascript": true
  },
  {
    "slug": "binary-tree-right-side-view",
    "title": "Binary Tree Right Side View",
    "pattern": "Trees",
    "difficulty": "Medium",
    "order": 54,
    "questionUrl": "https://neetcode.io/problems/binary-tree-right-side-view",
    "sourceId": "binary-tree-right-side-view",
    "code": "0199-binary-tree-right-side-view",
    "python": true,
    "javascript": true
  },
  {
    "slug": "count-good-nodes-in-binary-tree",
    "title": "Count Good Nodes In Binary Tree",
    "pattern": "Trees",
    "difficulty": "Medium",
    "order": 55,
    "questionUrl": "https://neetcode.io/problems/count-good-nodes-in-binary-tree",
    "sourceId": "count-good-nodes-in-binary-tree",
    "code": "1448-count-good-nodes-in-binary-tree",
    "python": true,
    "javascript": true
  },
  {
    "slug": "validate-binary-search-tree",
    "title": "Validate Binary Search Tree",
    "pattern": "Trees",
    "difficulty": "Medium",
    "order": 56,
    "questionUrl": "https://neetcode.io/problems/valid-binary-search-tree",
    "sourceId": "valid-binary-search-tree",
    "code": "0098-validate-binary-search-tree",
    "python": true,
    "javascript": true
  },
  {
    "slug": "kth-smallest-element-in-a-bst",
    "title": "Kth Smallest Element In a Bst",
    "pattern": "Trees",
    "difficulty": "Medium",
    "order": 57,
    "questionUrl": "https://neetcode.io/problems/kth-smallest-integer-in-bst",
    "sourceId": "kth-smallest-integer-in-bst",
    "code": "0230-kth-smallest-element-in-a-bst",
    "python": true,
    "javascript": true
  },
  {
    "slug": "construct-binary-tree-from-preorder-and-inorder-traversal",
    "title": "Construct Binary Tree From Preorder And Inorder Traversal",
    "pattern": "Trees",
    "difficulty": "Medium",
    "order": 58,
    "questionUrl": "https://neetcode.io/problems/binary-tree-from-preorder-and-inorder-traversal",
    "sourceId": "binary-tree-from-preorder-and-inorder-traversal",
    "code": "0105-construct-binary-tree-from-preorder-and-inorder-traversal",
    "python": true,
    "javascript": true
  },
  {
    "slug": "binary-tree-maximum-path-sum",
    "title": "Binary Tree Maximum Path Sum",
    "pattern": "Trees",
    "difficulty": "Hard",
    "order": 59,
    "questionUrl": "https://neetcode.io/problems/binary-tree-maximum-path-sum",
    "sourceId": "binary-tree-maximum-path-sum",
    "code": "0124-binary-tree-maximum-path-sum",
    "python": true,
    "javascript": true
  },
  {
    "slug": "serialize-and-deserialize-binary-tree",
    "title": "Serialize And Deserialize Binary Tree",
    "pattern": "Trees",
    "difficulty": "Hard",
    "order": 60,
    "questionUrl": "https://neetcode.io/problems/serialize-and-deserialize-binary-tree",
    "sourceId": "serialize-and-deserialize-binary-tree",
    "code": "0297-serialize-and-deserialize-binary-tree",
    "python": true,
    "javascript": true
  },
  {
    "slug": "implement-trie-prefix-tree",
    "title": "Implement Trie Prefix Tree",
    "pattern": "Tries",
    "difficulty": "Medium",
    "order": 61,
    "questionUrl": "https://neetcode.io/problems/implement-prefix-tree",
    "sourceId": "implement-prefix-tree",
    "code": "0208-implement-trie-prefix-tree",
    "python": true,
    "javascript": true
  },
  {
    "slug": "design-add-and-search-words-data-structure",
    "title": "Design Add And Search Words Data Structure",
    "pattern": "Tries",
    "difficulty": "Medium",
    "order": 62,
    "questionUrl": "https://neetcode.io/problems/design-word-search-data-structure",
    "sourceId": "design-word-search-data-structure",
    "code": "0211-design-add-and-search-words-data-structure",
    "python": true,
    "javascript": true
  },
  {
    "slug": "word-search-ii",
    "title": "Word Search II",
    "pattern": "Tries",
    "difficulty": "Hard",
    "order": 63,
    "questionUrl": "https://neetcode.io/problems/search-for-word-ii",
    "sourceId": "search-for-word-ii",
    "code": "0212-word-search-ii",
    "python": true,
    "javascript": true
  },
  {
    "slug": "kth-largest-element-in-a-stream",
    "title": "Kth Largest Element In a Stream",
    "pattern": "Heap / Priority Queue",
    "difficulty": "Easy",
    "order": 64,
    "questionUrl": "https://neetcode.io/problems/kth-largest-integer-in-a-stream",
    "sourceId": "kth-largest-integer-in-a-stream",
    "code": "0703-kth-largest-element-in-a-stream",
    "python": true,
    "javascript": true
  },
  {
    "slug": "last-stone-weight",
    "title": "Last Stone Weight",
    "pattern": "Heap / Priority Queue",
    "difficulty": "Easy",
    "order": 65,
    "questionUrl": "https://neetcode.io/problems/last-stone-weight",
    "sourceId": "last-stone-weight",
    "code": "1046-last-stone-weight",
    "python": true,
    "javascript": true
  },
  {
    "slug": "k-closest-points-to-origin",
    "title": "K Closest Points to Origin",
    "pattern": "Heap / Priority Queue",
    "difficulty": "Medium",
    "order": 66,
    "questionUrl": "https://neetcode.io/problems/k-closest-points-to-origin",
    "sourceId": "k-closest-points-to-origin",
    "code": "0973-k-closest-points-to-origin",
    "python": true,
    "javascript": true
  },
  {
    "slug": "kth-largest-element-in-an-array",
    "title": "Kth Largest Element In An Array",
    "pattern": "Heap / Priority Queue",
    "difficulty": "Medium",
    "order": 67,
    "questionUrl": "https://neetcode.io/problems/kth-largest-element-in-an-array",
    "sourceId": "kth-largest-element-in-an-array",
    "code": "0215-kth-largest-element-in-an-array",
    "python": true,
    "javascript": true
  },
  {
    "slug": "task-scheduler",
    "title": "Task Scheduler",
    "pattern": "Heap / Priority Queue",
    "difficulty": "Medium",
    "order": 68,
    "questionUrl": "https://neetcode.io/problems/task-scheduling",
    "sourceId": "task-scheduling",
    "code": "0621-task-scheduler",
    "python": true,
    "javascript": true
  },
  {
    "slug": "design-twitter",
    "title": "Design Twitter",
    "pattern": "Heap / Priority Queue",
    "difficulty": "Medium",
    "order": 69,
    "questionUrl": "https://neetcode.io/problems/design-twitter-feed",
    "sourceId": "design-twitter-feed",
    "code": "0355-design-twitter",
    "python": true,
    "javascript": true
  },
  {
    "slug": "find-median-from-data-stream",
    "title": "Find Median From Data Stream",
    "pattern": "Heap / Priority Queue",
    "difficulty": "Hard",
    "order": 70,
    "questionUrl": "https://neetcode.io/problems/find-median-in-a-data-stream",
    "sourceId": "find-median-in-a-data-stream",
    "code": "0295-find-median-from-data-stream",
    "python": true,
    "javascript": true
  },
  {
    "slug": "subsets",
    "title": "Subsets",
    "pattern": "Backtracking",
    "difficulty": "Medium",
    "order": 71,
    "questionUrl": "https://neetcode.io/problems/subsets",
    "sourceId": "subsets",
    "code": "0078-subsets",
    "python": true,
    "javascript": true
  },
  {
    "slug": "combination-sum",
    "title": "Combination Sum",
    "pattern": "Backtracking",
    "difficulty": "Medium",
    "order": 72,
    "questionUrl": "https://neetcode.io/problems/combination-target-sum",
    "sourceId": "combination-target-sum",
    "code": "0039-combination-sum",
    "python": true,
    "javascript": true
  },
  {
    "slug": "permutations",
    "title": "Permutations",
    "pattern": "Backtracking",
    "difficulty": "Medium",
    "order": 73,
    "questionUrl": "https://neetcode.io/problems/permutations",
    "sourceId": "permutations",
    "code": "0046-permutations",
    "python": true,
    "javascript": true
  },
  {
    "slug": "subsets-ii",
    "title": "Subsets II",
    "pattern": "Backtracking",
    "difficulty": "Medium",
    "order": 74,
    "questionUrl": "https://neetcode.io/problems/subsets-ii",
    "sourceId": "subsets-ii",
    "code": "0090-subsets-ii",
    "python": true,
    "javascript": true
  },
  {
    "slug": "combination-sum-ii",
    "title": "Combination Sum II",
    "pattern": "Backtracking",
    "difficulty": "Medium",
    "order": 75,
    "questionUrl": "https://neetcode.io/problems/combination-target-sum-ii",
    "sourceId": "combination-target-sum-ii",
    "code": "0040-combination-sum-ii",
    "python": true,
    "javascript": true
  },
  {
    "slug": "word-search",
    "title": "Word Search",
    "pattern": "Backtracking",
    "difficulty": "Medium",
    "order": 76,
    "questionUrl": "https://neetcode.io/problems/search-for-word",
    "sourceId": "search-for-word",
    "code": "0079-word-search",
    "python": true,
    "javascript": true
  },
  {
    "slug": "palindrome-partitioning",
    "title": "Palindrome Partitioning",
    "pattern": "Backtracking",
    "difficulty": "Medium",
    "order": 77,
    "questionUrl": "https://neetcode.io/problems/palindrome-partitioning",
    "sourceId": "palindrome-partitioning",
    "code": "0131-palindrome-partitioning",
    "python": true,
    "javascript": true
  },
  {
    "slug": "letter-combinations-of-a-phone-number",
    "title": "Letter Combinations of a Phone Number",
    "pattern": "Backtracking",
    "difficulty": "Medium",
    "order": 78,
    "questionUrl": "https://neetcode.io/problems/combinations-of-a-phone-number",
    "sourceId": "combinations-of-a-phone-number",
    "code": "0017-letter-combinations-of-a-phone-number",
    "python": true,
    "javascript": true
  },
  {
    "slug": "n-queens",
    "title": "N Queens",
    "pattern": "Backtracking",
    "difficulty": "Hard",
    "order": 79,
    "questionUrl": "https://neetcode.io/problems/n-queens",
    "sourceId": "n-queens",
    "code": "0051-n-queens",
    "python": true,
    "javascript": true
  },
  {
    "slug": "number-of-islands",
    "title": "Number of Islands",
    "pattern": "Graphs",
    "difficulty": "Medium",
    "order": 80,
    "questionUrl": "https://neetcode.io/problems/count-number-of-islands",
    "sourceId": "count-number-of-islands",
    "code": "0200-number-of-islands",
    "python": true,
    "javascript": true
  },
  {
    "slug": "clone-graph",
    "title": "Clone Graph",
    "pattern": "Graphs",
    "difficulty": "Medium",
    "order": 81,
    "questionUrl": "https://neetcode.io/problems/clone-graph",
    "sourceId": "clone-graph",
    "code": "0133-clone-graph",
    "python": true,
    "javascript": true
  },
  {
    "slug": "max-area-of-island",
    "title": "Max Area of Island",
    "pattern": "Graphs",
    "difficulty": "Medium",
    "order": 82,
    "questionUrl": "https://neetcode.io/problems/max-area-of-island",
    "sourceId": "max-area-of-island",
    "code": "0695-max-area-of-island",
    "python": true,
    "javascript": true
  },
  {
    "slug": "pacific-atlantic-water-flow",
    "title": "Pacific Atlantic Water Flow",
    "pattern": "Graphs",
    "difficulty": "Medium",
    "order": 83,
    "questionUrl": "https://neetcode.io/problems/pacific-atlantic-water-flow",
    "sourceId": "pacific-atlantic-water-flow",
    "code": "0417-pacific-atlantic-water-flow",
    "python": true,
    "javascript": true
  },
  {
    "slug": "surrounded-regions",
    "title": "Surrounded Regions",
    "pattern": "Graphs",
    "difficulty": "Medium",
    "order": 84,
    "questionUrl": "https://neetcode.io/problems/surrounded-regions",
    "sourceId": "surrounded-regions",
    "code": "0130-surrounded-regions",
    "python": true,
    "javascript": true
  },
  {
    "slug": "rotting-oranges",
    "title": "Rotting Oranges",
    "pattern": "Graphs",
    "difficulty": "Medium",
    "order": 85,
    "questionUrl": "https://neetcode.io/problems/rotting-fruit",
    "sourceId": "rotting-fruit",
    "code": "0994-rotting-oranges",
    "python": true,
    "javascript": true
  },
  {
    "slug": "walls-and-gates",
    "title": "Walls And Gates",
    "pattern": "Graphs",
    "difficulty": "Medium",
    "order": 86,
    "questionUrl": "https://neetcode.io/problems/islands-and-treasure",
    "sourceId": "islands-and-treasure",
    "code": "0286-walls-and-gates",
    "python": true,
    "javascript": true
  },
  {
    "slug": "course-schedule",
    "title": "Course Schedule",
    "pattern": "Graphs",
    "difficulty": "Medium",
    "order": 87,
    "questionUrl": "https://neetcode.io/problems/course-schedule",
    "sourceId": "course-schedule",
    "code": "0207-course-schedule",
    "python": true,
    "javascript": true
  },
  {
    "slug": "course-schedule-ii",
    "title": "Course Schedule II",
    "pattern": "Graphs",
    "difficulty": "Medium",
    "order": 88,
    "questionUrl": "https://neetcode.io/problems/course-schedule-ii",
    "sourceId": "course-schedule-ii",
    "code": "0210-course-schedule-ii",
    "python": true,
    "javascript": true
  },
  {
    "slug": "redundant-connection",
    "title": "Redundant Connection",
    "pattern": "Graphs",
    "difficulty": "Medium",
    "order": 89,
    "questionUrl": "https://neetcode.io/problems/redundant-connection",
    "sourceId": "redundant-connection",
    "code": "0684-redundant-connection",
    "python": true,
    "javascript": true
  },
  {
    "slug": "number-of-connected-components-in-an-undirected-graph",
    "title": "Number of Connected Components In An Undirected Graph",
    "pattern": "Graphs",
    "difficulty": "Medium",
    "order": 90,
    "questionUrl": "https://neetcode.io/problems/count-connected-components",
    "sourceId": "count-connected-components",
    "code": "0323-number-of-connected-components-in-an-undirected-graph",
    "python": true,
    "javascript": true
  },
  {
    "slug": "graph-valid-tree",
    "title": "Graph Valid Tree",
    "pattern": "Graphs",
    "difficulty": "Medium",
    "order": 91,
    "questionUrl": "https://neetcode.io/problems/valid-tree",
    "sourceId": "valid-tree",
    "code": "0261-graph-valid-tree",
    "python": true,
    "javascript": true
  },
  {
    "slug": "word-ladder",
    "title": "Word Ladder",
    "pattern": "Graphs",
    "difficulty": "Hard",
    "order": 92,
    "questionUrl": "https://neetcode.io/problems/word-ladder",
    "sourceId": "word-ladder",
    "code": "0127-word-ladder",
    "python": true,
    "javascript": true
  },
  {
    "slug": "reconstruct-itinerary",
    "title": "Reconstruct Itinerary",
    "pattern": "Advanced Graphs",
    "difficulty": "Hard",
    "order": 93,
    "questionUrl": "https://neetcode.io/problems/reconstruct-flight-path",
    "sourceId": "reconstruct-flight-path",
    "code": "0332-reconstruct-itinerary",
    "python": true,
    "javascript": true
  },
  {
    "slug": "min-cost-to-connect-all-points",
    "title": "Min Cost to Connect All Points",
    "pattern": "Advanced Graphs",
    "difficulty": "Medium",
    "order": 94,
    "questionUrl": "https://neetcode.io/problems/min-cost-to-connect-points",
    "sourceId": "min-cost-to-connect-points",
    "code": "1584-min-cost-to-connect-all-points",
    "python": true,
    "javascript": true
  },
  {
    "slug": "network-delay-time",
    "title": "Network Delay Time",
    "pattern": "Advanced Graphs",
    "difficulty": "Medium",
    "order": 95,
    "questionUrl": "https://neetcode.io/problems/network-delay-time",
    "sourceId": "network-delay-time",
    "code": "0743-network-delay-time",
    "python": true,
    "javascript": true
  },
  {
    "slug": "swim-in-rising-water",
    "title": "Swim In Rising Water",
    "pattern": "Advanced Graphs",
    "difficulty": "Hard",
    "order": 96,
    "questionUrl": "https://neetcode.io/problems/swim-in-rising-water",
    "sourceId": "swim-in-rising-water",
    "code": "0778-swim-in-rising-water",
    "python": true,
    "javascript": true
  },
  {
    "slug": "alien-dictionary",
    "title": "Alien Dictionary",
    "pattern": "Advanced Graphs",
    "difficulty": "Hard",
    "order": 97,
    "questionUrl": "https://neetcode.io/problems/foreign-dictionary",
    "sourceId": "foreign-dictionary",
    "code": "0269-alien-dictionary",
    "python": true,
    "javascript": true
  },
  {
    "slug": "cheapest-flights-within-k-stops",
    "title": "Cheapest Flights Within K Stops",
    "pattern": "Advanced Graphs",
    "difficulty": "Medium",
    "order": 98,
    "questionUrl": "https://neetcode.io/problems/cheapest-flight-path",
    "sourceId": "cheapest-flight-path",
    "code": "0787-cheapest-flights-within-k-stops",
    "python": true,
    "javascript": true
  },
  {
    "slug": "climbing-stairs",
    "title": "Climbing Stairs",
    "pattern": "1-D Dynamic Programming",
    "difficulty": "Easy",
    "order": 99,
    "questionUrl": "https://neetcode.io/problems/climbing-stairs",
    "sourceId": "climbing-stairs",
    "code": "0070-climbing-stairs",
    "python": true,
    "javascript": true
  },
  {
    "slug": "min-cost-climbing-stairs",
    "title": "Min Cost Climbing Stairs",
    "pattern": "1-D Dynamic Programming",
    "difficulty": "Easy",
    "order": 100,
    "questionUrl": "https://neetcode.io/problems/min-cost-climbing-stairs",
    "sourceId": "min-cost-climbing-stairs",
    "code": "0746-min-cost-climbing-stairs",
    "python": true,
    "javascript": true
  },
  {
    "slug": "house-robber",
    "title": "House Robber",
    "pattern": "1-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 101,
    "questionUrl": "https://neetcode.io/problems/house-robber",
    "sourceId": "house-robber",
    "code": "0198-house-robber",
    "python": true,
    "javascript": true
  },
  {
    "slug": "house-robber-ii",
    "title": "House Robber II",
    "pattern": "1-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 102,
    "questionUrl": "https://neetcode.io/problems/house-robber-ii",
    "sourceId": "house-robber-ii",
    "code": "0213-house-robber-ii",
    "python": true,
    "javascript": true
  },
  {
    "slug": "longest-palindromic-substring",
    "title": "Longest Palindromic Substring",
    "pattern": "1-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 103,
    "questionUrl": "https://neetcode.io/problems/longest-palindromic-substring",
    "sourceId": "longest-palindromic-substring",
    "code": "0005-longest-palindromic-substring",
    "python": true,
    "javascript": true
  },
  {
    "slug": "palindromic-substrings",
    "title": "Palindromic Substrings",
    "pattern": "1-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 104,
    "questionUrl": "https://neetcode.io/problems/palindromic-substrings",
    "sourceId": "palindromic-substrings",
    "code": "0647-palindromic-substrings",
    "python": true,
    "javascript": true
  },
  {
    "slug": "decode-ways",
    "title": "Decode Ways",
    "pattern": "1-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 105,
    "questionUrl": "https://neetcode.io/problems/decode-ways",
    "sourceId": "decode-ways",
    "code": "0091-decode-ways",
    "python": true,
    "javascript": true
  },
  {
    "slug": "coin-change",
    "title": "Coin Change",
    "pattern": "1-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 106,
    "questionUrl": "https://neetcode.io/problems/coin-change",
    "sourceId": "coin-change",
    "code": "0322-coin-change",
    "python": true,
    "javascript": true
  },
  {
    "slug": "maximum-product-subarray",
    "title": "Maximum Product Subarray",
    "pattern": "1-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 107,
    "questionUrl": "https://neetcode.io/problems/maximum-product-subarray",
    "sourceId": "maximum-product-subarray",
    "code": "0152-maximum-product-subarray",
    "python": true,
    "javascript": true
  },
  {
    "slug": "word-break",
    "title": "Word Break",
    "pattern": "1-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 108,
    "questionUrl": "https://neetcode.io/problems/word-break",
    "sourceId": "word-break",
    "code": "0139-word-break",
    "python": true,
    "javascript": true
  },
  {
    "slug": "longest-increasing-subsequence",
    "title": "Longest Increasing Subsequence",
    "pattern": "1-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 109,
    "questionUrl": "https://neetcode.io/problems/longest-increasing-subsequence",
    "sourceId": "longest-increasing-subsequence",
    "code": "0300-longest-increasing-subsequence",
    "python": true,
    "javascript": true
  },
  {
    "slug": "partition-equal-subset-sum",
    "title": "Partition Equal Subset Sum",
    "pattern": "1-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 110,
    "questionUrl": "https://neetcode.io/problems/partition-equal-subset-sum",
    "sourceId": "partition-equal-subset-sum",
    "code": "0416-partition-equal-subset-sum",
    "python": true,
    "javascript": true
  },
  {
    "slug": "unique-paths",
    "title": "Unique Paths",
    "pattern": "2-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 111,
    "questionUrl": "https://neetcode.io/problems/count-paths",
    "sourceId": "count-paths",
    "code": "0062-unique-paths",
    "python": true,
    "javascript": true
  },
  {
    "slug": "longest-common-subsequence",
    "title": "Longest Common Subsequence",
    "pattern": "2-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 112,
    "questionUrl": "https://neetcode.io/problems/longest-common-subsequence",
    "sourceId": "longest-common-subsequence",
    "code": "1143-longest-common-subsequence",
    "python": true,
    "javascript": true
  },
  {
    "slug": "best-time-to-buy-and-sell-stock-with-cooldown",
    "title": "Best Time to Buy And Sell Stock With Cooldown",
    "pattern": "2-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 113,
    "questionUrl": "https://neetcode.io/problems/buy-and-sell-crypto-with-cooldown",
    "sourceId": "buy-and-sell-crypto-with-cooldown",
    "code": "0309-best-time-to-buy-and-sell-stock-with-cooldown",
    "python": true,
    "javascript": true
  },
  {
    "slug": "coin-change-ii",
    "title": "Coin Change II",
    "pattern": "2-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 114,
    "questionUrl": "https://neetcode.io/problems/coin-change-ii",
    "sourceId": "coin-change-ii",
    "code": "0518-coin-change-ii",
    "python": true,
    "javascript": true
  },
  {
    "slug": "target-sum",
    "title": "Target Sum",
    "pattern": "2-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 115,
    "questionUrl": "https://neetcode.io/problems/target-sum",
    "sourceId": "target-sum",
    "code": "0494-target-sum",
    "python": true,
    "javascript": true
  },
  {
    "slug": "interleaving-string",
    "title": "Interleaving String",
    "pattern": "2-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 116,
    "questionUrl": "https://neetcode.io/problems/interleaving-string",
    "sourceId": "interleaving-string",
    "code": "0097-interleaving-string",
    "python": true,
    "javascript": true
  },
  {
    "slug": "longest-increasing-path-in-a-matrix",
    "title": "Longest Increasing Path In a Matrix",
    "pattern": "2-D Dynamic Programming",
    "difficulty": "Hard",
    "order": 117,
    "questionUrl": "https://neetcode.io/problems/longest-increasing-path-in-matrix",
    "sourceId": "longest-increasing-path-in-matrix",
    "code": "0329-longest-increasing-path-in-a-matrix",
    "python": true,
    "javascript": true
  },
  {
    "slug": "distinct-subsequences",
    "title": "Distinct Subsequences",
    "pattern": "2-D Dynamic Programming",
    "difficulty": "Hard",
    "order": 118,
    "questionUrl": "https://neetcode.io/problems/count-subsequences",
    "sourceId": "count-subsequences",
    "code": "0115-distinct-subsequences",
    "python": true,
    "javascript": true
  },
  {
    "slug": "edit-distance",
    "title": "Edit Distance",
    "pattern": "2-D Dynamic Programming",
    "difficulty": "Medium",
    "order": 119,
    "questionUrl": "https://neetcode.io/problems/edit-distance",
    "sourceId": "edit-distance",
    "code": "0072-edit-distance",
    "python": true,
    "javascript": true
  },
  {
    "slug": "burst-balloons",
    "title": "Burst Balloons",
    "pattern": "2-D Dynamic Programming",
    "difficulty": "Hard",
    "order": 120,
    "questionUrl": "https://neetcode.io/problems/burst-balloons",
    "sourceId": "burst-balloons",
    "code": "0312-burst-balloons",
    "python": true,
    "javascript": true
  },
  {
    "slug": "regular-expression-matching",
    "title": "Regular Expression Matching",
    "pattern": "2-D Dynamic Programming",
    "difficulty": "Hard",
    "order": 121,
    "questionUrl": "https://neetcode.io/problems/regular-expression-matching",
    "sourceId": "regular-expression-matching",
    "code": "0010-regular-expression-matching",
    "python": true,
    "javascript": true
  },
  {
    "slug": "maximum-subarray",
    "title": "Maximum Subarray",
    "pattern": "Greedy",
    "difficulty": "Medium",
    "order": 122,
    "questionUrl": "https://neetcode.io/problems/maximum-subarray",
    "sourceId": "maximum-subarray",
    "code": "0053-maximum-subarray",
    "python": true,
    "javascript": true
  },
  {
    "slug": "jump-game",
    "title": "Jump Game",
    "pattern": "Greedy",
    "difficulty": "Medium",
    "order": 123,
    "questionUrl": "https://neetcode.io/problems/jump-game",
    "sourceId": "jump-game",
    "code": "0055-jump-game",
    "python": true,
    "javascript": true
  },
  {
    "slug": "jump-game-ii",
    "title": "Jump Game II",
    "pattern": "Greedy",
    "difficulty": "Medium",
    "order": 124,
    "questionUrl": "https://neetcode.io/problems/jump-game-ii",
    "sourceId": "jump-game-ii",
    "code": "0045-jump-game-ii",
    "python": true,
    "javascript": true
  },
  {
    "slug": "gas-station",
    "title": "Gas Station",
    "pattern": "Greedy",
    "difficulty": "Medium",
    "order": 125,
    "questionUrl": "https://neetcode.io/problems/gas-station",
    "sourceId": "gas-station",
    "code": "0134-gas-station",
    "python": true,
    "javascript": true
  },
  {
    "slug": "hand-of-straights",
    "title": "Hand of Straights",
    "pattern": "Greedy",
    "difficulty": "Medium",
    "order": 126,
    "questionUrl": "https://neetcode.io/problems/hand-of-straights",
    "sourceId": "hand-of-straights",
    "code": "0846-hand-of-straights",
    "python": true,
    "javascript": true
  },
  {
    "slug": "merge-triplets-to-form-target-triplet",
    "title": "Merge Triplets to Form Target Triplet",
    "pattern": "Greedy",
    "difficulty": "Medium",
    "order": 127,
    "questionUrl": "https://neetcode.io/problems/merge-triplets-to-form-target",
    "sourceId": "merge-triplets-to-form-target",
    "code": "1899-merge-triplets-to-form-target-triplet",
    "python": true,
    "javascript": true
  },
  {
    "slug": "partition-labels",
    "title": "Partition Labels",
    "pattern": "Greedy",
    "difficulty": "Medium",
    "order": 128,
    "questionUrl": "https://neetcode.io/problems/partition-labels",
    "sourceId": "partition-labels",
    "code": "0763-partition-labels",
    "python": true,
    "javascript": true
  },
  {
    "slug": "valid-parenthesis-string",
    "title": "Valid Parenthesis String",
    "pattern": "Greedy",
    "difficulty": "Medium",
    "order": 129,
    "questionUrl": "https://neetcode.io/problems/valid-parenthesis-string",
    "sourceId": "valid-parenthesis-string",
    "code": "0678-valid-parenthesis-string",
    "python": true,
    "javascript": true
  },
  {
    "slug": "insert-interval",
    "title": "Insert Interval",
    "pattern": "Intervals",
    "difficulty": "Medium",
    "order": 130,
    "questionUrl": "https://neetcode.io/problems/insert-new-interval",
    "sourceId": "insert-new-interval",
    "code": "0057-insert-interval",
    "python": true,
    "javascript": true
  },
  {
    "slug": "merge-intervals",
    "title": "Merge Intervals",
    "pattern": "Intervals",
    "difficulty": "Medium",
    "order": 131,
    "questionUrl": "https://neetcode.io/problems/merge-intervals",
    "sourceId": "merge-intervals",
    "code": "0056-merge-intervals",
    "python": true,
    "javascript": true
  },
  {
    "slug": "non-overlapping-intervals",
    "title": "Non Overlapping Intervals",
    "pattern": "Intervals",
    "difficulty": "Medium",
    "order": 132,
    "questionUrl": "https://neetcode.io/problems/non-overlapping-intervals",
    "sourceId": "non-overlapping-intervals",
    "code": "0435-non-overlapping-intervals",
    "python": true,
    "javascript": true
  },
  {
    "slug": "meeting-rooms",
    "title": "Meeting Rooms",
    "pattern": "Intervals",
    "difficulty": "Easy",
    "order": 133,
    "questionUrl": "https://neetcode.io/problems/meeting-schedule",
    "sourceId": "meeting-schedule",
    "code": "0252-meeting-rooms",
    "python": true,
    "javascript": true
  },
  {
    "slug": "meeting-rooms-ii",
    "title": "Meeting Rooms II",
    "pattern": "Intervals",
    "difficulty": "Medium",
    "order": 134,
    "questionUrl": "https://neetcode.io/problems/meeting-schedule-ii",
    "sourceId": "meeting-schedule-ii",
    "code": "0253-meeting-rooms-ii",
    "python": true,
    "javascript": true
  },
  {
    "slug": "minimum-interval-to-include-each-query",
    "title": "Minimum Interval to Include Each Query",
    "pattern": "Intervals",
    "difficulty": "Hard",
    "order": 135,
    "questionUrl": "https://neetcode.io/problems/minimum-interval-including-query",
    "sourceId": "minimum-interval-including-query",
    "code": "1851-minimum-interval-to-include-each-query",
    "python": true,
    "javascript": true
  },
  {
    "slug": "rotate-image",
    "title": "Rotate Image",
    "pattern": "Math & Geometry",
    "difficulty": "Medium",
    "order": 136,
    "questionUrl": "https://neetcode.io/problems/rotate-matrix",
    "sourceId": "rotate-matrix",
    "code": "0048-rotate-image",
    "python": true,
    "javascript": true
  },
  {
    "slug": "spiral-matrix",
    "title": "Spiral Matrix",
    "pattern": "Math & Geometry",
    "difficulty": "Medium",
    "order": 137,
    "questionUrl": "https://neetcode.io/problems/spiral-matrix",
    "sourceId": "spiral-matrix",
    "code": "0054-spiral-matrix",
    "python": true,
    "javascript": true
  },
  {
    "slug": "set-matrix-zeroes",
    "title": "Set Matrix Zeroes",
    "pattern": "Math & Geometry",
    "difficulty": "Medium",
    "order": 138,
    "questionUrl": "https://neetcode.io/problems/set-zeroes-in-matrix",
    "sourceId": "set-zeroes-in-matrix",
    "code": "0073-set-matrix-zeroes",
    "python": true,
    "javascript": true
  },
  {
    "slug": "happy-number",
    "title": "Happy Number",
    "pattern": "Math & Geometry",
    "difficulty": "Easy",
    "order": 139,
    "questionUrl": "https://neetcode.io/problems/non-cyclical-number",
    "sourceId": "non-cyclical-number",
    "code": "0202-happy-number",
    "python": true,
    "javascript": true
  },
  {
    "slug": "plus-one",
    "title": "Plus One",
    "pattern": "Math & Geometry",
    "difficulty": "Easy",
    "order": 140,
    "questionUrl": "https://neetcode.io/problems/plus-one",
    "sourceId": "plus-one",
    "code": "0066-plus-one",
    "python": true,
    "javascript": true
  },
  {
    "slug": "powx-n",
    "title": "Pow(x, n)",
    "pattern": "Math & Geometry",
    "difficulty": "Medium",
    "order": 141,
    "questionUrl": "https://neetcode.io/problems/pow-x-n",
    "sourceId": "pow-x-n",
    "code": "0050-powx-n",
    "python": true,
    "javascript": true
  },
  {
    "slug": "multiply-strings",
    "title": "Multiply Strings",
    "pattern": "Math & Geometry",
    "difficulty": "Medium",
    "order": 142,
    "questionUrl": "https://neetcode.io/problems/multiply-strings",
    "sourceId": "multiply-strings",
    "code": "0043-multiply-strings",
    "python": true,
    "javascript": true
  },
  {
    "slug": "detect-squares",
    "title": "Detect Squares",
    "pattern": "Math & Geometry",
    "difficulty": "Medium",
    "order": 143,
    "questionUrl": "https://neetcode.io/problems/count-squares",
    "sourceId": "count-squares",
    "code": "2013-detect-squares",
    "python": true,
    "javascript": true
  },
  {
    "slug": "single-number",
    "title": "Single Number",
    "pattern": "Bit Manipulation",
    "difficulty": "Easy",
    "order": 144,
    "questionUrl": "https://neetcode.io/problems/single-number",
    "sourceId": "single-number",
    "code": "0136-single-number",
    "python": true,
    "javascript": true
  },
  {
    "slug": "number-of-1-bits",
    "title": "Number of 1 Bits",
    "pattern": "Bit Manipulation",
    "difficulty": "Easy",
    "order": 145,
    "questionUrl": "https://neetcode.io/problems/number-of-one-bits",
    "sourceId": "number-of-one-bits",
    "code": "0191-number-of-1-bits",
    "python": true,
    "javascript": true
  },
  {
    "slug": "counting-bits",
    "title": "Counting Bits",
    "pattern": "Bit Manipulation",
    "difficulty": "Easy",
    "order": 146,
    "questionUrl": "https://neetcode.io/problems/counting-bits",
    "sourceId": "counting-bits",
    "code": "0338-counting-bits",
    "python": true,
    "javascript": true
  },
  {
    "slug": "reverse-bits",
    "title": "Reverse Bits",
    "pattern": "Bit Manipulation",
    "difficulty": "Easy",
    "order": 147,
    "questionUrl": "https://neetcode.io/problems/reverse-bits",
    "sourceId": "reverse-bits",
    "code": "0190-reverse-bits",
    "python": true,
    "javascript": true
  },
  {
    "slug": "missing-number",
    "title": "Missing Number",
    "pattern": "Bit Manipulation",
    "difficulty": "Easy",
    "order": 148,
    "questionUrl": "https://neetcode.io/problems/missing-number",
    "sourceId": "missing-number",
    "code": "0268-missing-number",
    "python": true,
    "javascript": true
  },
  {
    "slug": "sum-of-two-integers",
    "title": "Sum of Two Integers",
    "pattern": "Bit Manipulation",
    "difficulty": "Medium",
    "order": 149,
    "questionUrl": "https://neetcode.io/problems/sum-of-two-integers",
    "sourceId": "sum-of-two-integers",
    "code": "0371-sum-of-two-integers",
    "python": true,
    "javascript": true
  },
  {
    "slug": "reverse-integer",
    "title": "Reverse Integer",
    "pattern": "Bit Manipulation",
    "difficulty": "Medium",
    "order": 150,
    "questionUrl": "https://neetcode.io/problems/reverse-integer",
    "sourceId": "reverse-integer",
    "code": "0007-reverse-integer",
    "python": true,
    "javascript": true
  }
].map(Object.freeze));
